### PR TITLE
Merge Functionality of Environment and Configuration

### PR DESCRIPTION
**Pull request by rye**
This stems off of #77.

Here's the plan: throw together a system as follows:

* [x] Get rid of the `Configuration` and `ConfigurationFile` classes, mocking their functionality out into protected methods within whichever classes consume then.
* [x] Create a new `Environment` class.
* [x] Move the `@environment_variable` manipulation methods (`:environment` and `:environment=` in `FReCon` in `lib/frecon/base/variables.rb`) out into this new `Environment` class.
* [x] `Environment#initialize` should take a single argument (`variable`, which will be a Symbol, one of: `[:development, :production, :test]`), and should use that to initialize stuff based off of defaults.
* [x] Environment should be structured as a Hash. (Inherit from Hash?)
* [x] Environment should bootstrap itself according to a list of configuration files, and this list should be XDG Base Directory Specification (XDGBDS)-compliant.
  * [x] If an environment variable (in the `ENV` Hash) is present to replace the values in the list, it should be used.
  * [x] If a file is absent or malformed, nothing bad should happen (but, if it is malformed, a warning message should be printed)

### CODE REVIEW

**Comment by rye** [comment]
Here's the plan: throw together a system as follows:

* Get rid of the `Configuration` and `ConfigurationFile` classes, mocking their functionality out into protected methods within whichever classes consume then.
* Create a new `Environment` class.
* Move the `@environment_variable` manipulation methods (`:environment` and `:environment=` in `FReCon` in `lib/frecon/base/variables.rb`) out into this new `Environment` class.
* `Environment#initialize` should take a single argument (`variable`, which will be a Symbol, one of: `[:development, :production, :test]`), and should use that to initialize stuff based off of defaults.
* Environment should be structured as a Hash. (Inherit from Hash?)
* Environment should bootstrap itself according to a list of configuration files, and this list should be XDG Base Directory Specification (XDGBDS)-compliant.
  * If an environment variable (in the `ENV` Hash) is present to replace the values in the list, it should be used.
  * If a file is absent or malformed, nothing bad should happen (but, if it is malformed, a warning message should be printed)

**Comment by Sammidysam** [comment]
Wait, why are the `Configuration` classes being killed?  I didn't really understand the explanation thoroughly.

**Comment by rye** [comment]
The way I see it, `Configuration` is a part of `Environment`; `Environment` isn't a part of `Configuration`.

**Comment by Sammidysam** [comment]
I see it the opposite way around.

**Comment by rye** [comment]
The Environment is used to describe the constraints of the entire system that FReCon runs on, right? Having the Environment contain configuration values as well as the general environment variable (`:development`, `:test`, `:production`) just makes sense according to that definition.

**Comment by Sammidysam** [comment]
Yeah, that makes sense.  Honestly, either name is largely okay with me, because I can see it in multiple ways.  I just did not realize at the start that it was largely replacing `Configuration` with `Environment`, but now I understand and all is good.

**Comment by rye** [comment]
Yeah, originally I thought that it would be different in that I'd have both, but then I realized that I wanted to merge the two.

**Comment by rye** [comment]
@Sammidysam does this look good to you now? If you're too busy to check I can just go ahead and merge it.  Once I've merged this, I will also create a release and tag for `v1.3.0` and push the new version up to RubyGems.

**Comment by rye** [comment]
@Sammidysam gave me the black light (no response because busy) so I'll go ahead and merge.  We'll look at any problems if they come up.

**Pull request merged**
